### ISSUE TITLE
Xbuild XML project error

### ISSUE THREAD

**Issue by Hsad** [AshleyF/Color#3]
On both Windows 10 and Ubuntu 18 using xbuild I get this error

```
XBuild Engine Version 14.0
Mono, Version 6.12.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 7/15/2021 12:21:54 PM.
__________________________________________________
C:\Code\F#\Color\Color.sln:  warning : C:\Code\F#\Color\Machine\Machine.fsproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.
```
Which then repeats 5 times, for 4 different sections.  Only one subsection having a possibly useful error.

```
C:\Code\F#\Color\Color.sln:  warning : Don't know how to handle GlobalSection ExtensibilityGlobals, Ignoring.
Project "C:\Code\F#\Color\Color.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|Any CPU".
```

This might be an obvious thing, I've just never used F# or these tools before, and searches aren't making sense.
I just want to get confused by ColorForth, not by 10 other things before that.

**Comment by AshleyF** [comment]
Oh man, the Readme is outdated. The project files have be moved to .NET Core. I just [updated the docs](https://github.com/AshleyF/Color/blob/master/README.md).

Basically just need to [install the .NET SDK](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) and then `dotnet build Color.sln`.

Good luck with the fun of ColorForth confusion!

**Comment by Hsad** [comment]
Thanks!! I'll try this out tonight

**Comment by Hsad** [comment]
Got it working, Had to install the version 3.1.0 of the .NET framework first.  Was spitting out identical errors on Windows and Ubuntu.

Thanks for putting this together and still supporting it.
